version: "3.7"
services:
    db:
      image: postgres:12.4-alpine
      command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
      ports:
        - 54321:5432
      env_file: ./api/.env
    front:
      ports:
        - 3000:3000
      build:
        context: ./front
        dockerfile: ./Dockerfile
      volumes:
        - ./front:/code
    web:
      depends_on:
          - db
      ports:
          - 8000:8000
      env_file: ./api/.env
      environment:
          - PYTHONUNBUFFERED=1
          - APP_SERVICE=web
      build:
        context: ./api
        dockerfile: ./Dockerfile
      volumes:
        - ./api:/code
