# Generated by Django 3.1.3 on 2020-11-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField(blank=True, null=True, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('image_url', models.CharField(blank=True, max_length=355, null=True, verbose_name='Imagem')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('category', models.CharField(choices=[('CHILDISH', 'Infantil'), ('ADULT', 'Adulto')], default='CHILDISH', max_length=8, verbose_name='Categoria')),
                ('size', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], default='P', max_length=2, verbose_name='Tamanho')),
                ('price', models.DecimalField(decimal_places=8, max_digits=13, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_per_day', models.IntegerField(verbose_name='Venda por dia')),
                ('total_sell', models.DecimalField(decimal_places=8, max_digits=13, verbose_name='Total Vendido')),
                ('month', models.CharField(choices=[('JANUARY', 'Janeiro'), ('FEBRUARY', 'Fevereiro'), ('MARCH', 'Março'), ('APRIL', 'Abril'), ('MAY', 'Maio'), ('JUNE', 'Junho'), ('JULY', 'Julho'), ('AUGUST', 'Agosto'), ('SEPTEMBER', 'Setembro'), ('OCTOBER', 'Outubro'), ('NOVEMBER', 'Novembro'), ('DECEMBER', 'Dezembro')], default='JANUARY', max_length=9, verbose_name='Mês')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stock.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Gerenciamento de produto',
                'verbose_name_plural': 'Gerenciamento de produtos',
            },
        ),
    ]
